### ISSUE TITLE
[JENKINS-35375] Failed to scout hudson.plugins.timestamper.pipeline.TimestamperStep

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/timestamper-plugin#443]
<p>Working on our Jenkins 1.656 instance, when I upgraded the Timestamper plugin from 1.7.4 to 1.8.2 I saw the following errors in the Jenkins system log at startup:</p>

<pre>
Listed all plugins
Jun 06, 2016 2:05:11 PM WARNING hudson.ExtensionFinder$Sezpoz scout
Failed to scout hudson.plugins.timestamper.pipeline.TimestamperStep$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:662)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:383)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$9.onInitMilestoneAttained(Jenkins.java:976)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:79)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method)
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass(<span class="code-object">ClassLoader</span>.java:800)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:802)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1209)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:425)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 29 more

Jun 06, 2016 2:05:11 PM WARNING hudson.ExtensionFinder$Sezpoz _find
Failed to load hudson.plugins.timestamper.pipeline.TimestamperStep$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:626)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:257)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.<span class="code-object">Class</span>.newInstance(<span class="code-object">Class</span>.java:374)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:640)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:389)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$9.onInitMilestoneAttained(Jenkins.java:976)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:79)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method)
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass(<span class="code-object">ClassLoader</span>.java:800)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:802)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1209)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:425)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 39 more

Jun 06, 2016 2:05:11 PM WARNING hudson.ExtensionFinder$Sezpoz _find
Failed to load hudson.plugins.timestamper.pipeline.TimestamperStep$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:626)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:275)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.<span class="code-object">Class</span>.newInstance(<span class="code-object">Class</span>.java:374)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:640)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:389)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$9.onInitMilestoneAttained(Jenkins.java:976)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:79)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method)
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass(<span class="code-object">ClassLoader</span>.java:800)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:802)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1209)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:425)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 39 more
</pre>

<p>Downgrading to 1.7.4 cleared the errors.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=davida2009">davida2009</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-35375" target="_blank">Failed to scout hudson.plugins.timestamper.pipeline.TimestamperStep</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/stevengbrown.png" title="stevengbrown's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=stevengbrown">stevengbrown</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: timestamper-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-06-20T14:29:03+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 20251218-075729
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Working on our Jenkins 1.656 instance, when I upgraded the Timestamper plugin from 1.7.4 to 1.8.2 I saw the following errors in the Jenkins system log at startup:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Listed all plugins
Jun 06, 2016 2:05:11 PM WARNING hudson.ExtensionFinder$Sezpoz scout
Failed to scout hudson.plugins.timestamper.pipeline.TimestamperStep$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:662)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:383)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$9.onInitMilestoneAttained(Jenkins.java:976)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:79)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method)
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass(<span class="code-object">ClassLoader</span>.java:800)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:802)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1209)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:425)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 29 more

Jun 06, 2016 2:05:11 PM WARNING hudson.ExtensionFinder$Sezpoz _find
Failed to load hudson.plugins.timestamper.pipeline.TimestamperStep$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:626)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ExtensionFinder$GuiceFinder.&lt;init&gt;(ExtensionFinder.java:257)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.<span class="code-object">Class</span>.newInstance(<span class="code-object">Class</span>.java:374)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:640)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:389)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$9.onInitMilestoneAttained(Jenkins.java:976)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:79)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method)
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass(<span class="code-object">ClassLoader</span>.java:800)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:802)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1209)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:425)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 39 more

Jun 06, 2016 2:05:11 PM WARNING hudson.ExtensionFinder$Sezpoz _find
Failed to load hudson.plugins.timestamper.pipeline.TimestamperStep$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:626)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ExtensionFinder$GuiceFinder.&lt;init&gt;(ExtensionFinder.java:275)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.<span class="code-object">Class</span>.newInstance(<span class="code-object">Class</span>.java:374)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:640)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:615)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:389)
	at hudson.ExtensionList.load(ExtensionList.java:349)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at jenkins.model.Jenkins$9.onInitMilestoneAttained(Jenkins.java:976)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:79)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method)
	at java.lang.<span class="code-object">ClassLoader</span>.defineClass(<span class="code-object">ClassLoader</span>.java:800)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:802)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1209)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:425)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 39 more
</pre>
</div></div>

<p>Downgrading to 1.7.4 cleared the errors.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins 1.656</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>davida2009:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-35375?focusedId=261952&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-261952">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The warnings are fixed in Timestamper 1.8.3. Thanks.</p>
</pre>
</details>

</ul>
</details>

<p>The warnings are fixed in Timestamper 1.8.3. Thanks.</p>
